package net.androidsquad.prizejson;

public class priceModelClassn {
    String category;
    String motivation;
    String Laureates;
    String Id;
    String Firstname;
    String surname;
    String year;

    public PriceModelClass(String category,
            String motivation,
            String Laureates,
            String Id,
            String Firstname,
            String surname,
            String year) {
        this.id = id;
        this.category = category;
        this.motivation = motivation;
        this.Laureates = Laureates;
        this.Firstname = Firstname;
        this.surname = surname;
        this.year = year;
    }

    Public PriceModelClass() {
    }
    public String getid() {
    }



    }
}
